# backend/agents/presentation_agent.py — VIA Phase 4: PowerPoint Generator

import time
import logging
import uuid
from pathlib import Path

logger = logging.getLogger("AI-Digital-Company")
PROJECTS_BASE = Path("projects")

# ── Lazy color helpers (pptx is optional) ─────────────────────────────────────
# All pptx imports are deferred so the module can load without python-pptx.

def _rgb(r, g, b):
    """Create an RGBColor — only call inside functions that truly need pptx."""
    from pptx.dml.color import RGBColor
    return RGBColor(r, g, b)


def _get_colors():
    """Return the VIA colour palette dict. Called lazily inside generate_pptx."""
    return {
        "DARK_BG":   _rgb(1,   1,   8),
        "DARK_CARD": _rgb(10,  10,  30),
        "CYAN":      _rgb(0,   212, 255),
        "VIOLET":    _rgb(124, 58,  237),
        "GREEN":     _rgb(0,   255, 157),
        "MAGENTA":   _rgb(255, 0,   110),
        "WHITE":     _rgb(255, 255, 255),
        "GRAY":      _rgb(123, 163, 192),
        "DARK_GRAY": _rgb(42,  74,  96),
        "PINK":      _rgb(255, 77,  148),
        "PURPLE":    _rgb(192, 132, 252),
    }


def _blank_slide(prs):
    return prs.slides.add_slide(prs.slide_layouts[6])


def _set_bg(slide, color):
    slide.background.fill.solid()
    slide.background.fill.fore_color.rgb = color


def _add_rect(slide, left, top, width, height, color):
    from pptx.util import Inches
    sh = slide.shapes.add_shape(1, Inches(left), Inches(top), Inches(width), Inches(height))
    sh.fill.solid()
    sh.fill.fore_color.rgb = color
    sh.line.fill.background()
    return sh


def _add_text(slide, text, left, top, width, height, size, color, bold=False):
    from pptx.util import Inches, Pt
    tx = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    tf = tx.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = str(text)[:500]
    p.font.size = Pt(size)
    p.font.color.rgb = color
    p.font.bold = bold
    p.font.name = "Calibri"
    return tx


def _cover_slide(prs, task, job_id, C):
    slide = _blank_slide(prs)
    _set_bg(slide, C["DARK_BG"])
    _add_rect(slide, 0, 0, 16, 2.4, C["DARK_CARD"])
    _add_rect(slide, 0, 0, 0.18, 9, C["CYAN"])
    _add_text(slide, "VIA", 0.5, 0.25, 4, 1.4, 52, C["CYAN"], bold=True)
    _add_text(slide, "AUTONOMOUS AI DIGITAL TEAM  ·  PHASE 4 MNC ENGINE", 0.5, 1.6, 14, 0.6, 10, C["DARK_GRAY"])
    _add_text(slide, task[:120], 0.5, 3.0, 15, 2.0, 28, C["WHITE"], bold=True)
    _add_text(slide, f"Job ID: {job_id}  ·  Generated by VIA", 0.5, 8.3, 15, 0.5, 10, C["DARK_GRAY"])


def _section_slide(prs, title, bullets, accent, C):
    from pptx.util import Inches, Pt
    slide = _blank_slide(prs)
    _set_bg(slide, C["DARK_BG"])
    _add_rect(slide, 0, 0, 16, 1.3, C["DARK_CARD"])
    _add_rect(slide, 0, 0, 0.18, 9, accent)
    _add_text(slide, title, 0.4, 0.2, 15, 0.9, 22, accent, bold=True)
    tx = slide.shapes.add_textbox(Inches(0.5), Inches(1.6), Inches(15), Inches(7.0))
    tf = tx.text_frame
    tf.word_wrap = True
    for i, b in enumerate(bullets[:10]):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.text = f"▸  {str(b)[:200]}"
        p.font.size = Pt(15)
        p.font.color.rgb = C["WHITE"] if i == 0 else C["GRAY"]
        p.font.name = "Calibri"
        p.space_after = Pt(6)


def _dept_meta(C):
    """Return department metadata — called lazily inside generate_pptx."""
    return {
        "backend":      ("⚙️ Backend Engineering",    C["CYAN"]),
        "frontend":     ("🎨 Frontend Engineering",    C["VIOLET"]),
        "security":     ("🔐 Security Architecture",   C["MAGENTA"]),
        "devops":       ("🚀 DevOps & Deployment",     C["GREEN"]),
        "ai_research":  ("🧠 AI Research",             C["PURPLE"]),
        "architecture": ("📐 Solutions Architecture",  C["GREEN"]),
        "hr":           ("👥 Human Resources",         C["PINK"]),
        "finance":      ("💰 Finance & ROI",           C["GREEN"]),
        "marketing":    ("📣 Marketing & GTM",         C["PURPLE"]),
    }


def generate_pptx(task: str, job_id: str, ceo_strategy: dict, departments: dict) -> str:
    from pptx import Presentation
    from pptx.util import Inches

    # Initialize colors lazily
    C = _get_colors()
    DEPT_META = _dept_meta(C)

    prs = Presentation()
    prs.slide_width  = Inches(16)
    prs.slide_height = Inches(9)

    # Cover
    _cover_slide(prs, task, job_id, C)

    # CEO Strategy
    strat = ceo_strategy or {}
    _section_slide(prs, "🎯 CEO Strategy", [
        f"Short-Term (0-3 months): {strat.get('short_term_strategy','N/A')[:200]}",
        f"Long-Term Vision (6-24 months): {strat.get('long_term_vision','N/A')[:200]}",
        "Execution: 9 autonomous AI agents assigned to all departments",
        "Pipeline: GitHub auto-push → Render auto-deploy",
    ], C["MAGENTA"], C)

    # Department slides
    for dept, data in departments.items():
        if data.get("status") != "success":
            continue
        meta = DEPT_META.get(dept)
        if not meta:
            continue
        title, color = meta
        output = data.get("output", {})
        bullets = [f"Confidence: {round(data.get('confidence',0)*100)}%  ·  Time: {data.get('execution_time_seconds',0)}s"]
        for k, v in output.items():
            if k in ("department", "department_path"):
                continue
            if isinstance(v, str) and len(v) > 10:
                bullets.append(f"{k.replace('_',' ').title()}: {v[:160]}")
            elif isinstance(v, list) and v:
                bullets.append(f"{k.replace('_',' ').title()}: {', '.join(str(x)[:50] for x in v[:4])}")
        _section_slide(prs, title, bullets, color, C)

    # Timeline
    _section_slide(prs, "📅 Execution Timeline", [
        "Week 1-2:  Architecture design + DB schema",
        "Week 3-6:  Backend API + Security hardening",
        "Week 7-9:  Frontend build + Integration tests",
        "Week 10-11: DevOps setup + CI/CD pipeline",
        "Week 12:   Staging deployment + QA",
        "Month 3+:  Production launch + Marketing",
    ], C["GREEN"], C)

    # Next Steps
    n = len([d for d in departments.values() if d.get("status") == "success"])
    _section_slide(prs, "✅ Next Steps", [
        f"Review outputs from {n} departments",
        "Merge into unified technical specification",
        "Approve budget & headcount (see Finance slide)",
        "Set up Render account + link GitHub repository",
        "Schedule engineering kickoff meeting",
        "Launch marketing campaign (see Marketing slide)",
    ], C["CYAN"], C)

    # Save
    out_dir = PROJECTS_BASE / f"pptx_{job_id}"
    out_dir.mkdir(parents=True, exist_ok=True)
    safe = "".join(c if c.isalnum() or c in " _-" else "_" for c in task[:40]).strip()
    out_path = out_dir / f"VIA_{safe}.pptx"
    prs.save(str(out_path))
    logger.info(f"PPTX saved | {out_path} | {len(prs.slides)} slides")
    return str(out_path)


async def presentation_agent(task: str, ceo_strategy: str = "", project_brief: dict = None, inter_context: str = "") -> dict:
    """Standard agent signature — generates a presentation summary report."""
    start = time.time()
    logger.info(f"Presentation Agent | {task[:60]}")
    try:
        from backend.core.llm_provider import llm
        prompt = f"""You are VIA's Presentation Director. Create a concise executive presentation outline.

Task: {task}
CEO Strategy: {ceo_strategy}
{f'Context: {inter_context[:500]}' if inter_context else ''}

Create a 6-slide presentation outline with:
1. Cover slide (title + tagline)
2. Problem Statement
3. Solution Architecture
4. Key Features (5 bullets)
5. Go-to-Market Timeline
6. Next Steps & Call to Action

Format each slide as: SLIDE N: Title | Content"""
        output = await llm.agenerate(prompt)
        dur = round(time.time() - start, 2)
        return {
            "department": "Presentation",
            "presentation_outline": output or "",
            "slide_count": 6,
            "summary": f"Executive presentation outline for '{task[:60]}' — 6 slides covering problem, solution, features, timeline.",
        }
    except Exception as e:
        dur = round(time.time() - start, 2)
        logger.error(f"Presentation Agent failed | {e}")
        return {
            "department": "Presentation",
            "error": str(e),
            "summary": "Presentation generation failed.",
        }
